name: VIVIA Rentals CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "staging" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build with Webpack
        run: npx webpack --mode production

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: compiled-app
          path: dist/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to Netlify
        run: npm run deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  stripe-webhook-validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Validate Stripe Webhook Secret
        run: |
          if [ -z "${{ secrets.STRIPE_WEBHOOK_SECRET }}" ]; then
            echo "Missing Stripe webhook secret!"
            exit 1
          fi
          echo "Stripe Webhook Secret is properly configured."
